name: portfolio
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  cupertino_icons: ^0.1.2
  flutter_circular_chart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true